language: node_js
node_js: '6.3'
script: make publish
dist: trusty
sudo: required
env:
  secure: GNyTwfWlX19g+2NMmApTf2X3gZr8aavKvMboKkc23btQuomW/VNXBdEcuGnkDzqI1vPTHF8byQUgWZneXM9wGyBDxZXzxwCglwNj2rtr136pSG0+iRyV7P4ryamEwNVMj0IOaFgM8H5uX4AAjllh9sdVJbrDRSuQYibpMLYmJ493EdXeqWJQSuzHgin/XlPegKRihu/ZtWpEvZ+siahuVsBhyC8H9IcPItcfSOdt3jLhvhaDrhV5Y2BbYEQeWqFSfCtLegMeB7aDtbZMWyI3+Sw81clUXEcrFhSTHg6IQZ0yw1rpWVOxMbcIsOx8X5wbzi6d3SA4KkLjh4YjMlxD6KvhowL5nMV1y9X3bi1UjvjQmmevUYaw3fzJMMbJ7lT6X3uMApg2e+BAWICbIOfq0ioCeYIsx+cv0pVVpH+9SEDwcDAdt2VdNW3WMgD2BQGIfd1zXROVzm+QJ7NTneetgkBg/zaeju0UnFq3WmC6NukWAFJmSCNHEhKWiJkoALka4zqt+V7X5gHri/LXBlzJPRB55GCEohi/2Xmp1sA+w3LCqLUzVA9vthhB8ewEhgdx//MpnMbkPo1wIAHVU8z8Fhh67hpuMsJjMNHWnmFQ3FL1c88qZmZh8tGxWRX5cO32eaBC1t3S+vxxlaKGT9Kqag9o9onDj2NuZ/M/+xLK6Zk=
addons:
  apt:
    packages:
      - git
